<div class="page-header"> <h1 >
اتصل بنا <small>نحب أن نسمع رأيك</small></h1>
</div>
<div class="row"> <div class="col-sm-12" ><strong>الرجاء الاتصال بنا باستخدام معلومات الاتصال التالية:</strong></div>
</div>
<div class="row">
<div class="col-sm-4"> <div >Mobile: +971 (0)5 797 8805</div><div> <div >Email: <a href="mailto:mhh1422@hotmail.com">mhh1422@hotmail.com</a></div> <div >Skype: muhannad.shelleh</div>
</div>
</div></div>