<div class="jumbotron">
    <h1>T4F Web Portal</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce gravida volutpat ultrices. Fusce vehicula ultricies risus, eu ullamcorper massa dignissim.</p>
    <div>
        <a href="&lt;?= base_url(">" class="btn btn-primary btn-lg" role="button">Learn more »</a>
    </div>
</div>
<div class="row">
    <div class="col-sm-4">
<div class='lead'>
عنوان
</div>
<p>
محتوى
</p>
    </div>
    <div class="col-sm-4">
<div class='lead'>
عنوان
</div>
<p>
محتوى
</p>
    </div>
    <div class="col-sm-4">
<div class='lead'>
عنوان
</div>
<p>
محتوى
</p>
    </div>
</div>