<div class="row chat-message" style="margin-bottom:10px; padding-bottom:10px;">
    <div class="col-sm-3 col-lg-2">
        <strong><?= $writer ?></strong>
    </div>
    <div class="col-sm-5 col-lg-7">
        <?= $script ?>
    </div>
    <div class="col-sm-4 col-lg-3">
        <span class="text-muted visible-lg visible-md">
            <?= $time ?>
        </span>
        <span class="text-muted hidden-lg hidden-md">
            <?= $shortened_time ?>
        </span>
    </div>
</div>