<?php
if (!isset($window_title)) {
    $window_title = $title;
}
/* @var $this MY_Loader */
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?= $window_title ?> - T4F</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta charset="utf-8"> 
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

        <!-- Bootstrap -->
        <?php if ($this->controller()->getLanguage() == "arabic"): ?>
            <link href="<?= base_url("assets/css/bootstrap-ar.css") ?>" rel="stylesheet">
            <link href="<?= base_url("assets/css/bootstrap-theme-ar.css") ?>" rel="stylesheet">
            <link href="<?= base_url("assets/css/bootstrap_some.css") ?>" rel="stylesheet">
        <?php else: ?>
            <link href="<?= base_url("assets/css/bootstrap.css") ?>" rel="stylesheet">
            <link href="<?= base_url("assets/css/bootstrap.theme2.min.css") ?>" rel="stylesheet">
            <link href="<?= base_url("assets/css/bootstrap_some.css") ?>" rel="stylesheet">
        <?php endif; ?>
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link href="<?= base_url("assets/css/style.css") ?>" rel="stylesheet">
        <link href="<?= base_url("assets/css/classes.css") ?>" rel="stylesheet">
        <style>
            body{
                padding-top:50px;
            }
        </style>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script type="text/javascript">
            var systemCorePath = "<?= base_url() ?>";
        </script>
        <script src="https://code.jquery.com/jquery.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="<?= base_url("assets/js/bootstrap.min.js") ?>"></script>
        <script src="<?= base_url("assets/js/jquery.exts.js") ?>"></script>
        <script src="<?= base_url("assets/js/jquery.tbs.showdal.js") ?>"></script>
        <script src="<?= base_url("assets/js/jquery.tbs.showlert.js") ?>"></script>
        <script src="<?= base_url("assets/js/functions.js") ?>"></script>
        <script>
            fw.core.setupUnexpireableSession();
        </script>

    </head>
    <body>

        <?php
        // $this->extend('templates/common/navigation.phtml') ?>