<footer>
    <div class="">
        <ul class="nav nav-footer">
            <li><a href="<?= base_url("home") ?>"><?= __("Home") ?></a></li>
            <li><a href="<?= base_url("about") ?>"><?= __("About") ?></a></li>
            <li><a href="<?= base_url("contact_us") ?>"><?= __("Contact Us") ?></a></li>
        </ul>
    </div>
    <div class="">
        <?= __("&copy; 2013, T4F.") ?>
    </div>
    <div class="">
        <?= __("Developed by") ?> <a href="http://www.itvision-sa.com" target="_blank"><?= __("IT Vision") ?></a>.
    </div>
</footer>