<div class="page-header">
<h1>
Contact Us
<small>
We would like to hear from you
</small>
</h1>
</div>
<div class="row">
<div class="col-sm-12"><strong>Please contact us on the following information:</strong></div>
</div>
<div class="row">
<div class="col-sm-4">
<div>Mobile: +123 (0)4 567 8910</div><div>
<div>Email: <a href="mailto:support@yourdomain.com">support@yourdomain.com</a></div>
<div>Skype: yourSkypeID</div>
</div>
</div></div>