<div class="container">
    <div class="page-header">
        <h1>
            <?= __($title) ?>
            <small>
                <?php if ($is_me): ?>
                    <a href="<?= base_url($return_url) ?>"><?= __($sub_title) ?></a> <span class="text-muted"> &gt; </span> <?= __("Change Password") ?>
                <?php else: ?>
                    <a href="<?= base_url("users") ?>"><?= __($sub_title) ?></a> <span class="text-muted"> &gt; </span> <a href="<?= base_url("$return_url") ?>"><?= $model->col('full_name', $model->col('username')) ?></a> <span class="text-muted"> &gt; </span> <?= __("Change Password") ?>
                <?php endif; ?>
            </small>
        </h1>
    </div>
    <?php if ($operation_result): ?>
        <?= operationResult($operation_result) ?>
    <?php endif; ?>
    <div class="row">
        <form id="change-password-form" class="form form-horizontal col-sm-7 col-md-6 col-lg-5" action="<?= base_url("users/do_change_password") ?>" method="post" role="form">
            <input type="hidden" name="user_id" value="<?= $model->col('id') ?>" />
            <input type="hidden" name="return_url" value="<?= $return_url ?>" />
            <?php if ($is_me): ?>
                <div class="form-group">
                    <label for="oldPasswordTxt" class="col-sm-5 control-label"><?= __("Old password") ?></label>
                    <div class="col-sm-7">
                        <input type="password" name="old_password" id="oldPasswordTxt" placeholder="<?= __("Your old password") ?>" class="form-control required" required="required" />
                        <div class="error start-hidden old required" for="oldPasswordTxt"><?= __("Old password is required") ?>!</div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="form-group">
                <label for="newPasswordTxt" class="col-sm-5 control-label"><?= __("New password") ?></label>
                <div class="col-sm-7">
                    <input type="password" name="new_password" id="newPasswordTxt" placeholder="<?= __("Enter new password") ?>" class="form-control required" required="required" />
                    <div class="error start-hidden new required" for="newPasswordTxt"><?= __("New password is required!") ?></div>
                    <div class="error start-hidden new length" for="newPasswordTxt"><?= __("New password should be at least 5 characters!") ?></div>
                </div>
            </div>
            <div class="form-group">
                <label for="confirmPasswordTxt" class="col-sm-5 control-label"><?= __("Confirm password") ?></label>
                <div class="col-sm-7">
                    <input type="password" name="confirm_password" id="confirmPasswordTxt" placeholder="<?= __("Confirm new password") ?>" class="form-control required" required="required" />
                    <div class="error start-hidden confirm required" for="confirmPasswordTxt"><?= __("Confirm password can not be empty.") ?></div>
                    <div class="error start-hidden confirm match" for="confirmPasswordTxt"><?= __("Confirm password should match the new password.") ?></div>
                </div>
            </div>
            <hr />
            <div class="text-right">
                <a class="btn btn-default pull-left" href="<?= base_url($return_url) ?>"><?= __("Cancel") ?></a>&nbsp;
                <button class="btn btn-primary" type="submit"><?= __("Change Password") ?></button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function() {

        $("#change-password-form input").keypress(function() {
            $(this).parents('.form-group').removeClass('has-error').find('.error').hide();
        });

        $("#change-password-form").submit(function() {
            $(this).find('.error').hide();
            if ($("#oldPasswordTxt").length > 0) {
                if (!$("#oldPasswordTxt").val()) {
                    $(".old.required").show();
                    $("#oldPasswordTxt").focus().parents(".form-group").addClass("has-error");
                    return false;
                }
            }
            if (!$("#newPasswordTxt").val()) {
                $(".new.required").show();
                $("#newPasswordTxt").focus().parents(".form-group").addClass("has-error");
                return false;
            }
            if ($("#newPasswordTxt").val().length < 5) {
                $(".new.length").show();
                $("#newPasswordTxt").focus().parents(".form-group").addClass("has-error");
                return false;
            }
            if (!$("#confirmPasswordTxt").val()) {
                $(".confirm.required").show();
                $("#confirmPasswordTxt").focus().parents(".form-group").addClass("has-error");
                return false;
            }
            if ($("#confirmPasswordTxt").val() != $("#newPasswordTxt").val()) {
                $(".confirm.match").show();
                $("#confirmPasswordTxt").focus().parents(".form-group").addClass("has-error");
                return false;
            }
            return true;
        });
    });
</script>